// ── Shared atoms from @ibatexas/ui ──────────────────────────────────────────
export { Button, buttonVariants } from '@ibatexas/ui/atoms'
export { Badge, badgeVariants } from '@ibatexas/ui/atoms'
export { DataTable } from '@ibatexas/ui/atoms'
export { StatCard } from '@ibatexas/ui/atoms'
export { Switch } from '@ibatexas/ui/atoms'

// ── Web-only atoms ──────────────────────────────────────────────────────────
export { LinkButton } from './Button'
export { Heading, Text, textVariants } from './Typography'
export { Label } from './Label'
export { Image } from './Image'
export { Card } from './Card'
export { TextField } from './TextField'
export { IconButton } from './IconButton'
export { TextArea } from './TextArea'
export { Select } from './Select'
export { Checkbox } from './Checkbox'
export { RadioGroup } from './RadioGroup'
export { Tabs } from './Tabs'
export { HeroVideo } from './HeroVideo'
export { Skeleton } from './Skeleton'
export { ScrollReveal } from './ScrollReveal'
