// ── Shared atoms from @ibatexas/ui ──────────────────────────────────────────
export { Button, buttonVariants } from '@ibatexas/ui/atoms'
export { Badge, badgeVariants, type BadgeProps } from '@ibatexas/ui/atoms'
export { DataTable } from '@ibatexas/ui/atoms'
export { StatCard } from '@ibatexas/ui/atoms'
export { Switch } from '@ibatexas/ui/atoms'
export { Label, type LabelProps } from '@ibatexas/ui/atoms'
export { TextField } from '@ibatexas/ui/atoms'
export { TextArea } from '@ibatexas/ui/atoms'
export { Select, type SelectOption, type SelectProps } from '@ibatexas/ui/atoms'
export { Checkbox } from '@ibatexas/ui/atoms'
export { RadioGroup, type RadioOption, type RadioGroupProps } from '@ibatexas/ui/atoms'
export { Tabs, type TabItem } from '@ibatexas/ui/atoms'
export { Card } from '@ibatexas/ui/atoms'
export { Skeleton } from '@ibatexas/ui/atoms'
export { IconButton, iconButtonVariants, type IconButtonProps } from '@ibatexas/ui/atoms'

// ── Web-only atoms ──────────────────────────────────────────────────────────
export { LinkButton } from './Button'
export { Heading, Text, textVariants } from './Typography'
export { Image } from './Image'
export { HeroVideo } from './HeroVideo'
export { ScrollReveal } from './ScrollReveal'
export { ErrorBoundary } from './ErrorBoundary'
export { JsonLd } from './JsonLd'
export { Container } from './Container'
export { Section } from './Section'
export { MarqueeStrip } from './MarqueeStrip'
