// clients/auth-fixture.ts — T1a-4 authFixture: offline JWT minting, cookie
// transport, fingerprint-gated.
//
// There is NO fake-Twilio seam in apps/api (routes/auth.ts always builds the
// real Verify client) — minting test JWTs offline with the stack's own test
// secrets is the only journey auth path (plan-v2 fact #37). This fixture
// replicates the API's EXACT issued-claim shape WITHOUT importing apps/api
// (check-bypass leg 7); every claim below cites its source of truth:
//
//   Customer (issueJwtToken, apps/api/src/routes/auth.ts:166-184):
//     { sub: customerId, userType: "customer", jti: randomUUID(),
//       aud: "token" }, expiresIn '4h' — signed HS256 with JWT_SECRET via the
//     default @fastify/jwt instance (apps/api/src/server.ts:70-75, fast-jwt
//     under the hood; string secret ⇒ HS256). Verification reads the `token`
//     httpOnly cookie (server.ts:73 `cookie: { cookieName: "token" }`) with
//     `verify: { allowedAud: "token" }` (server.ts:74) — the API has NO
//     Authorization-header path for customers, so delivery is STRICTLY the
//     `token=` cookie.
//
//   Staff (issueStaffJwtToken, apps/api/src/routes/auth.ts:186-206):
//     { sub: staffId, userType: "staff", role, jti: randomUUID(),
//       aud: "staff_token" }, expiresIn '8h' — signed with STAFF_JWT_SECRET
//     via the namespaced staff instance (server.ts:89-93,
//     `verify: { allowedAud: "staff_token" }`; the secrets MUST differ —
//     server.ts:83-88 refuses to boot otherwise). Delivery is STRICTLY the
//     `staff_token=` cookie (middleware/auth.ts:140).
//
//   App-level claim checks the minted shape must survive
//   (apps/api/src/middleware/auth.ts):
//     :96-98    staff tokens arriving on the customer cookie are rejected;
//     :116-118  empty/whitespace-only `sub` is rejected (both tiers);
//     :123-128  aud↔cookie binding (`aud: "token"` for the customer cookie);
//     :162-167  aud↔cookie binding (`aud: "staff_token"` for staff);
//     :67-79    jti revocation list — Redis lookup, FAIL-CLOSED: a request
//               carrying a jti cannot authenticate while Redis is down (503).
//               The fixture only guarantees jti UNIQUENESS per mint (fresh
//               randomUUID); it never manages revocation lists.
//     :178-179  staff additionally requires an ACTIVE row in ibx_domain.staff
//               (per-request re-check). Seeding path: `ibx auth create-staff`
//               (packages/cli/src/commands/auth.ts:168-218) — the fixture
//               itself ONLY mints; it never seeds.
//
// CONTAINMENT (governance-critical): every minting function REFUSES with
// TestFingerprintRequiredError unless IBX_TEST_FINGERPRINT is set (D-010:
// only the ephemeral test profile carries that var — .env.test, generated by
// scripts/gen-env-test.sh; /health exposes it as `testFingerprint`). Combined
// with secret-distinctness (the test stack's JWT secrets are generated per
// run and never match dev/prod), a forged-token path against a non-test
// stack requires BOTH stealing a prod secret AND faking the fingerprint.
// This helper lives ONLY in @ibatexas/journeys — check-bypass leg 6 keeps
// the package un-importable from apps/* and non-test packages/*.

import { randomUUID } from "node:crypto"
import { createSigner } from "fast-jwt"
import { TEST_FINGERPRINT_ENV } from "../harness/preflight.js"

// ── Contract pins (cited above) ──────────────────────────────────────────────

/** Customer JWT cookie name (apps/api/src/server.ts:73). */
export const CUSTOMER_COOKIE_NAME = "token"

/** Staff JWT cookie name (apps/api/src/middleware/auth.ts:140). */
export const STAFF_COOKIE_NAME = "staff_token"

/** Customer token TTL issued by the API (apps/api/src/routes/auth.ts:182). */
export const CUSTOMER_TOKEN_TTL = "4h"

/** Staff token TTL issued by the API (apps/api/src/routes/auth.ts:204). */
export const STAFF_TOKEN_TTL = "8h"

/** Staff roles (apps/api/src/middleware/auth.ts:21; cli auth.ts:176). */
export const STAFF_ROLES = ["OWNER", "MANAGER", "ATTENDANT"] as const

export type StaffRole = (typeof STAFF_ROLES)[number]

export type AuthCookieName =
  | typeof CUSTOMER_COOKIE_NAME
  | typeof STAFF_COOKIE_NAME

// ── Named errors ─────────────────────────────────────────────────────────────

/**
 * The containment gate refused to mint: IBX_TEST_FINGERPRINT is absent.
 * Only the ephemeral test profile sets that var (D-010) — minting against
 * anything else is forbidden by construction.
 */
export class TestFingerprintRequiredError extends Error {
  constructor(fn: string) {
    super(
      `${fn} refused: ${TEST_FINGERPRINT_ENV} is not set. The authFixture ` +
        "mints ONLY inside the ephemeral test profile (.env.test carries the " +
        "fingerprint; dev/prod never do) — this gate is governance, not a " +
        "configuration hint.",
    )
    this.name = "TestFingerprintRequiredError"
  }
}

/** Invalid minting/cookie-assembly options (named, fail-fast). */
export class AuthFixtureOptionError extends Error {
  constructor(message: string) {
    super(message)
    this.name = "AuthFixtureOptionError"
  }
}

// ── Result shape ─────────────────────────────────────────────────────────────

/**
 * A minted token plus its cookie transport. `cookie` is the ready-to-send
 * `name=value` pair (JWS compact serialization is cookie-safe — base64url,
 * no escaping needed); combine several with `cookieHeader()`.
 */
export interface MintedToken {
  /** Compact HS256 JWS. */
  token: string
  /** The ONLY cookie the API reads this token from. */
  cookieName: AuthCookieName
  /** `${cookieName}=${token}` — a single Cookie-header pair. */
  cookie: string
  /** The `sub` claim (customerId / staffId). */
  sub: string
  /** Unique per mint (fresh randomUUID — revocation-list friendly). */
  jti: string
}

// ── Internals ────────────────────────────────────────────────────────────────

function requireTestFingerprint(fn: string): void {
  const fingerprint = process.env[TEST_FINGERPRINT_ENV]
  if (fingerprint === undefined || fingerprint.trim() === "") {
    throw new TestFingerprintRequiredError(fn)
  }
}

/**
 * Resolves the `sub` from the `customerId|sub` (or `staffId|sub`) aliases.
 * Mirrors middleware/auth.ts:116-118 — an empty/whitespace `sub` would be
 * silently unauthenticated server-side, so the fixture fails fast instead.
 */
function resolveSub(
  fn: string,
  alias: string,
  aliasValue: string | undefined,
  sub: string | undefined,
): string {
  if (aliasValue !== undefined && sub !== undefined && aliasValue !== sub) {
    throw new AuthFixtureOptionError(
      `${fn}: \`${alias}\` ("${aliasValue}") and \`sub\` ("${sub}") disagree — pass one (they are aliases)`,
    )
  }
  const resolved = aliasValue ?? sub
  if (resolved === undefined || resolved.trim() === "") {
    throw new AuthFixtureOptionError(
      `${fn}: a non-empty \`${alias}\` (or \`sub\`) is required — the API rejects empty/whitespace sub (middleware/auth.ts:116-118)`,
    )
  }
  return resolved
}

function requireSecret(fn: string, name: string, value: string | undefined): string {
  if (value === undefined || value.trim() === "") {
    throw new AuthFixtureOptionError(
      `${fn}: \`${name}\` is required (the test stack's generated secret — .env.test; never a dev/prod value)`,
    )
  }
  return value
}

function signHs256(
  payload: Record<string, unknown>,
  secret: string,
  expiresIn: number | string,
): string {
  // String secret + HS256 = exactly how the API signs (@fastify/jwt over
  // fast-jwt, apps/api/src/server.ts:70-75). `aud` rides IN the payload, the
  // same way issueJwtToken/issueStaffJwtToken put it there.
  const sign = createSigner({ key: secret, algorithm: "HS256", expiresIn })
  return sign(payload)
}

// ── Minting ──────────────────────────────────────────────────────────────────

export interface MintCustomerTokenOptions {
  /** Customer id — becomes the JWT `sub`. Alias of `sub`; pass one. */
  customerId?: string
  /** JWT `sub` claim. Alias of `customerId`; pass one. */
  sub?: string
  /** The test stack's JWT_SECRET (HS256 — .env.test). */
  jwtSecret: string
  /** Override TTL (fast-jwt `expiresIn`). Default: the API's own 4h. */
  expiresIn?: number | string
}

/**
 * Mints a customer JWT exactly as issueJwtToken does
 * (apps/api/src/routes/auth.ts:177-183) and binds it to the `token=` cookie.
 * REFUSES without IBX_TEST_FINGERPRINT (containment — see module header).
 */
export function mintCustomerToken(options: MintCustomerTokenOptions): MintedToken {
  requireTestFingerprint("mintCustomerToken")
  const sub = resolveSub("mintCustomerToken", "customerId", options.customerId, options.sub)
  const secret = requireSecret("mintCustomerToken", "jwtSecret", options.jwtSecret)
  const jti = randomUUID()
  const token = signHs256(
    // Claim-for-claim mirror of routes/auth.ts:178-181.
    { sub, userType: "customer", jti, aud: CUSTOMER_COOKIE_NAME },
    secret,
    options.expiresIn ?? CUSTOMER_TOKEN_TTL,
  )
  return {
    token,
    cookieName: CUSTOMER_COOKIE_NAME,
    cookie: `${CUSTOMER_COOKIE_NAME}=${token}`,
    sub,
    jti,
  }
}

export interface MintStaffTokenOptions {
  /**
   * Staff id — becomes the JWT `sub`. Alias of `sub`; pass one.
   * MUST reference an ACTIVE ibx_domain.staff row: middleware/auth.ts:178-179
   * re-checks the row on EVERY request, so a minted-but-unseeded staff token
   * is rejected regardless of signature validity. Seed via
   * `ibx auth create-staff --phone ... --name ... --role ...` first.
   */
  staffId?: string
  /** JWT `sub` claim. Alias of `staffId`; pass one. */
  sub?: string
  /** Role claim — must match the seeded row's role for honest journeys. */
  role: StaffRole
  /** The test stack's STAFF_JWT_SECRET (MUST differ from JWT_SECRET — server.ts:83-88). */
  staffJwtSecret: string
  /** Override TTL (fast-jwt `expiresIn`). Default: the API's own 8h. */
  expiresIn?: number | string
}

/**
 * Mints a staff JWT exactly as issueStaffJwtToken does
 * (apps/api/src/routes/auth.ts:198-205) and binds it to the `staff_token=`
 * cookie — staff auth is STRICTLY that cookie (middleware/auth.ts:140); there
 * is no header path. REFUSES without IBX_TEST_FINGERPRINT.
 */
export function mintStaffToken(options: MintStaffTokenOptions): MintedToken {
  requireTestFingerprint("mintStaffToken")
  const sub = resolveSub("mintStaffToken", "staffId", options.staffId, options.sub)
  const secret = requireSecret("mintStaffToken", "staffJwtSecret", options.staffJwtSecret)
  if (!STAFF_ROLES.includes(options.role)) {
    throw new AuthFixtureOptionError(
      `mintStaffToken: \`role\` must be one of ${STAFF_ROLES.join(" | ")} (got "${String(options.role)}")`,
    )
  }
  const jti = randomUUID()
  const token = signHs256(
    // Claim-for-claim mirror of routes/auth.ts:199-203.
    { sub, userType: "staff", role: options.role, jti, aud: STAFF_COOKIE_NAME },
    secret,
    options.expiresIn ?? STAFF_TOKEN_TTL,
  )
  return {
    token,
    cookieName: STAFF_COOKIE_NAME,
    cookie: `${STAFF_COOKIE_NAME}=${token}`,
    sub,
    jti,
  }
}

// ── Cookie transport ─────────────────────────────────────────────────────────

/**
 * Assembles a Cookie header value from minted tokens, for fetch/SSE use
 * (shared with the ChatClient, T1a-5):
 *
 *   fetch(url, { headers: { cookie: cookieHeader(customer) } })
 *
 * Pairs are joined RFC-6265 style (`"; "`). Duplicate cookie names are
 * refused — the API reads exactly one token per cookie, so two values for
 * the same name means the journey is confused about its identity.
 */
export function cookieHeader(...minted: readonly MintedToken[]): string {
  if (minted.length === 0) {
    throw new AuthFixtureOptionError("cookieHeader: at least one minted token is required")
  }
  const seen = new Set<string>()
  for (const m of minted) {
    if (seen.has(m.cookieName)) {
      throw new AuthFixtureOptionError(
        `cookieHeader: duplicate cookie "${m.cookieName}" — one token per cookie name`,
      )
    }
    seen.add(m.cookieName)
  }
  return minted.map((m) => m.cookie).join("; ")
}
