// harness/test-env.ts — .env.test loader for `ibx journey run` (T1a-13).
//
// The journey harness runs OUTSIDE the process-compose test profile, but the
// T1a-11a env contract (.env.test, gitignored, generated by
// scripts/gen-env-test.sh) is what carries the fingerprint, the stack's
// secrets, the oracle URL, and the model pins.
//
// OVERRIDE SEMANTICS (default): the test-profile contract is AUTHORITATIVE
// for a journey run — every key in .env.test replaces whatever is in
// process.env. This is deliberate: the ibx CLI preloads the developer's
// root .env via dotenv at startup, so by the time the run command executes,
// process.env already carries DEV values (JWT_SECRET, DATABASE_URL, …);
// "shell wins" would silently mint dev-secret JWTs against the test stack
// (surfaced live: 401 on checkout — the cookie was signed with the dev
// secret). It also mirrors the process-compose test profile, whose
// in-command `set -a; . ./.env.test` sourcing overrides inherited values
// for the same reason. Keys NOT present in .env.test keep their ambient
// values.
//
// SECRETS DISCIPLINE: values are never logged, never returned to CLI output,
// and never embedded in error messages. The parser is the same minimal
// KEY=VALUE reader the T1a-4/T1a-5 live tests use (no dotenv dependency).

import { readFileSync } from "node:fs"

/** Minimal KEY=VALUE parser (comments + blank lines skipped, quotes stripped). */
export function parseEnvFile(raw: string): Record<string, string> {
  const out: Record<string, string> = {}
  for (const line of raw.split("\n")) {
    const trimmed = line.trim()
    if (trimmed === "" || trimmed.startsWith("#")) continue
    const eq = trimmed.indexOf("=")
    if (eq <= 0) continue
    const key = trimmed.slice(0, eq).trim()
    let value = trimmed.slice(eq + 1).trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    out[key] = value
  }
  return out
}

export interface LoadTestEnvResult {
  /** Keys injected into process.env (absent before). Names only — never values. */
  injected: string[]
  /** Keys whose ambient value was REPLACED by the .env.test value. */
  overridden: string[]
  /** Keys already carrying exactly the .env.test value (no-op). */
  identical: string[]
}

export interface LoadTestEnvOptions {
  /**
   * Replace ambient process.env values with the file's (default TRUE — see
   * header: the CLI's dotenv preload of the dev .env must never leak into
   * the test plane). `false` restores dotenv-style shell-wins semantics.
   */
  override?: boolean
}

/**
 * Load `.env.test` into `process.env` (override semantics by default; see
 * header). Returns which keys were injected/overridden/identical — names
 * only, for the trace. Throws when the file is unreadable (the caller
 * decides whether that is fatal — the preflight will refuse anyway without
 * the fingerprint).
 */
export function loadTestEnv(
  envFilePath: string,
  options: LoadTestEnvOptions = {},
): LoadTestEnvResult {
  const override = options.override ?? true
  const parsed = parseEnvFile(readFileSync(envFilePath, "utf8"))
  const injected: string[] = []
  const overridden: string[] = []
  const identical: string[] = []
  for (const [key, value] of Object.entries(parsed)) {
    const current = process.env[key]
    if (current === undefined) {
      process.env[key] = value
      injected.push(key)
    } else if (current === value) {
      identical.push(key)
    } else if (override) {
      process.env[key] = value
      overridden.push(key)
    }
  }
  return { injected, overridden, identical }
}
