// harness/test-env.ts — .env.test loader for `ibx journey run` (T1a-13).
//
// The journey harness runs OUTSIDE the process-compose test profile, but the
// T1a-11a env contract (.env.test, gitignored, generated by
// scripts/gen-env-test.sh) is what carries the fingerprint, the stack's
// secrets, the oracle URL, and the model pins. `loadTestEnv` parses the file
// and injects every key into `process.env` — SHELL WINS: a key already
// present in the environment is never overridden (the dotenv convention, and
// how test-stack-up.sh exports the same file).
//
// SECRETS DISCIPLINE: values are never logged, never returned to CLI output,
// and never embedded in error messages. The parser is the same minimal
// KEY=VALUE reader the T1a-4/T1a-5 live tests use (no dotenv dependency).

import { readFileSync } from "node:fs"

/** Minimal KEY=VALUE parser (comments + blank lines skipped, quotes stripped). */
export function parseEnvFile(raw: string): Record<string, string> {
  const out: Record<string, string> = {}
  for (const line of raw.split("\n")) {
    const trimmed = line.trim()
    if (trimmed === "" || trimmed.startsWith("#")) continue
    const eq = trimmed.indexOf("=")
    if (eq <= 0) continue
    const key = trimmed.slice(0, eq).trim()
    let value = trimmed.slice(eq + 1).trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    out[key] = value
  }
  return out
}

export interface LoadTestEnvResult {
  /** Keys injected into process.env (absent before). Names only — never values. */
  injected: string[]
  /** Keys present in the file but already set in the shell (shell won). */
  preserved: string[]
}

/**
 * Load `.env.test` into `process.env` (shell wins; see header). Returns which
 * keys were injected vs preserved — names only, for the trace. Throws when
 * the file is unreadable (the caller decides whether that is fatal — the
 * preflight will refuse anyway without the fingerprint).
 */
export function loadTestEnv(envFilePath: string): LoadTestEnvResult {
  const parsed = parseEnvFile(readFileSync(envFilePath, "utf8"))
  const injected: string[] = []
  const preserved: string[] = []
  for (const [key, value] of Object.entries(parsed)) {
    if (process.env[key] === undefined) {
      process.env[key] = value
      injected.push(key)
    } else {
      preserved.push(key)
    }
  }
  return { injected, preserved }
}
