// Shared Medusa HTTP client — single source of truth for all Medusa API calls.
//
// Auth model:
//  - Admin routes use a Bearer JWT obtained from /auth/user/emailpass with
//    MEDUSA_ADMIN_EMAIL / MEDUSA_ADMIN_PASSWORD. The token is cached in-memory
//    for this process and refreshed proactively before expiry (and reactively
//    on 401 as a safety net).
//  - Store routes require an `x-publishable-api-key` header. The publishable
//    key is regenerated by Medusa bootstrap on every `db reset`, so we resolve
//    it at runtime from the admin API (first call) and cache it for the
//    process lifetime. No env var — the key lives in Medusa's DB and is
//    resolved on demand.
//
// Used by: cart tools, API routes, OrderService (via injection), jobs,
// subscribers, catalog enrichment. Throws MedusaRequestError with structured
// fields (statusCode, responseText).

const MEDUSA_URL = process.env.MEDUSA_URL ?? "http://localhost:9000"
const DEFAULT_TIMEOUT_MS = 10_000

/** Convert Medusa v2 price (reais, e.g. 89.00) to centavos (8900). */
export function reaisToCentavos(amount: number): number {
  return Math.round(amount * 100)
}

// ── Error class ──────────────────────────────────────────────────────────────

export class MedusaRequestError extends Error {
  readonly statusCode: number
  readonly upstream = "Medusa" as const
  readonly responseText: string

  constructor(statusCode: number, responseText: string, path: string) {
    super(`Medusa ${statusCode}: ${path}`)
    this.name = "MedusaRequestError"
    this.statusCode = statusCode
    this.responseText = responseText
  }
}

// ── Admin JWT cache ──────────────────────────────────────────────────────────

type CachedToken = { token: string; expiresAt: number }
let adminTokenCache: CachedToken | null = null
let adminTokenInflight: Promise<string> | null = null

const ADMIN_TOKEN_SAFETY_WINDOW_MS = 60_000 // refresh 1 min before expiry

async function getAdminToken(forceRefresh = false): Promise<string> {
  const now = Date.now()
  if (
    !forceRefresh &&
    adminTokenCache &&
    adminTokenCache.expiresAt - ADMIN_TOKEN_SAFETY_WINDOW_MS > now
  ) {
    return adminTokenCache.token
  }
  // Coalesce concurrent refreshes so boot-time bursts share a single login.
  if (adminTokenInflight) return adminTokenInflight

  adminTokenInflight = (async () => {
    const email = process.env.MEDUSA_ADMIN_EMAIL
    const password = process.env.MEDUSA_ADMIN_PASSWORD
    if (!email || !password) {
      throw new Error(
        "MEDUSA_ADMIN_EMAIL / MEDUSA_ADMIN_PASSWORD must be set for Medusa admin auth",
      )
    }
    const res = await fetch(`${MEDUSA_URL}/auth/user/emailpass`, {
      method: "POST",
      signal: AbortSignal.timeout(DEFAULT_TIMEOUT_MS),
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ email, password }),
    })
    if (!res.ok) {
      throw new MedusaRequestError(res.status, await res.text(), "/auth/user/emailpass")
    }
    const { token } = (await res.json()) as { token: string }
    // Decode the `exp` claim without pulling in a JWT library — the payload
    // is the second segment of `h.p.s`, base64url-encoded JSON.
    const payload = JSON.parse(
      Buffer.from(token.split(".")[1], "base64url").toString("utf8"),
    ) as { exp: number }
    adminTokenCache = { token, expiresAt: payload.exp * 1000 }
    return token
  })().finally(() => {
    adminTokenInflight = null
  })

  return adminTokenInflight
}

// ── Admin API (Bearer JWT via emailpass) ─────────────────────────────────────

export async function medusaAdmin(path: string, options?: RequestInit): Promise<unknown> {
  const run = async (forceRefresh: boolean): Promise<Response> => {
    const token = await getAdminToken(forceRefresh)
    return fetch(`${MEDUSA_URL}${path}`, {
      ...options,
      signal: options?.signal ?? AbortSignal.timeout(DEFAULT_TIMEOUT_MS),
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${token}`,
        ...options?.headers,
      },
    })
  }

  let res = await run(false)
  if (res.status === 401) {
    // Cached token may have been invalidated server-side; retry once.
    res = await run(true)
  }
  if (!res.ok) {
    const text = await res.text()
    console.error(`[medusa-admin] ${res.status} ${path}: ${text}`)
    throw new MedusaRequestError(res.status, text, path)
  }
  return res.json()
}

// ── Publishable key resolver ─────────────────────────────────────────────────

let publishableKeyCache: string | null = null
let publishableKeyInflight: Promise<string> | null = null

async function getPublishableKey(forceRefresh = false): Promise<string> {
  if (!forceRefresh && publishableKeyCache) return publishableKeyCache
  if (publishableKeyInflight) return publishableKeyInflight

  publishableKeyInflight = (async () => {
    const data = (await medusaAdmin(
      "/admin/api-keys?type=publishable&limit=1",
    )) as { api_keys?: Array<{ token: string }> }
    const token = data.api_keys?.[0]?.token
    if (!token) {
      throw new Error("No publishable API key found in Medusa — did the bootstrap run?")
    }
    publishableKeyCache = token
    return token
  })().finally(() => {
    publishableKeyInflight = null
  })

  return publishableKeyInflight
}

// ── Store API (x-publishable-api-key) ────────────────────────────────────────

export async function medusaStore(path: string, options?: RequestInit): Promise<unknown> {
  const run = async (forceRefresh: boolean): Promise<Response> => {
    const key = await getPublishableKey(forceRefresh)
    return fetch(`${MEDUSA_URL}${path}`, {
      ...options,
      signal: options?.signal ?? AbortSignal.timeout(DEFAULT_TIMEOUT_MS),
      headers: {
        "x-publishable-api-key": key,
        "Content-Type": "application/json",
        ...options?.headers,
      },
    })
  }

  let res = await run(false)
  if (res.status === 400) {
    // The bootstrap publishable key may have rotated (e.g. after db reset
    // while this process was running). Drop cache and try once more.
    res = await run(true)
  }
  if (!res.ok) {
    const text = await res.text()
    const reqBody = options?.body ? String(options.body).slice(0, 500) : "(no body)"
    console.error(
      `[medusa-store] ${res.status} ${path}\n  request: ${reqBody}\n  response: ${text.slice(0, 500)}`,
    )
    throw new MedusaRequestError(res.status, text, path)
  }
  return res.json()
}
