// @generated by claimdef-compiler from cart-empty.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): 326b8fbec240273bca09d0371d27eadd2b1dcb6b4920e338d6dae942dfa1ffd3
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const CART_EMPTY_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "cart_empty",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": true,
  "perResourceKey": true,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "cart_item_added",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "cart_empty",
    "path": [
      "emptinessText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const CART_EMPTY_TEMPLATE = {
  "claimType": "CART_EMPTY",
  "posture": "validated",
  "slots": [
    {
      "kind": "LITERAL",
      "text": "Seu carrinho está "
    },
    {
      "kind": "PROPOSITION",
      "claimType": "CART_EMPTY",
      "field": "emptinessText"
    },
    {
      "kind": "LITERAL",
      "text": " no momento — quer dar uma olhada no cardápio?"
    }
  ]
} satisfies Template;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const CART_EMPTY_DEFINITION = {
  "type": "CART_EMPTY",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "cart_empty",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": true,
  "valueBinding": {
    "key": "cart_empty",
    "path": [
      "emptinessText"
    ]
  },
  "valueProjections": [
    {
      "field": "emptinessText",
      "key": "cart_empty",
      "path": [
        "emptinessText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "LITERAL",
        "text": "Seu carrinho está "
      },
      {
        "kind": "PROPOSITION",
        "claimType": "CART_EMPTY",
        "field": "emptinessText"
      },
      {
        "kind": "LITERAL",
        "text": " no momento — quer dar uma olhada no cardápio?"
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "cart_item_added",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const CART_EMPTY_ID = "CART_EMPTY@1";

