// @generated by claimdef-compiler from cart-contents.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): 89a5359ed25021bb8d951618453ff91ea16469efabb85bce634e6856e7578e7a
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec, RegistryClaimType } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const CART_CONTENTS_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "cart_contents",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": true,
  "perResourceKey": true,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "cart_cleared",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "cart_contents",
    "path": [
      "itemsSummaryText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const CART_CONTENTS_TEMPLATE = {
  "claimType": "CART_CONTENTS",
  "posture": "validated",
  "slots": [
    {
      "kind": "LITERAL",
      "text": "No seu carrinho: "
    },
    {
      "kind": "PROPOSITION",
      "claimType": "CART_CONTENTS",
      "field": "itemsSummaryText"
    },
    {
      "kind": "LITERAL",
      "text": "."
    }
  ]
} satisfies Template;

/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */
export const CART_CONTENTS_CLOSURE = {
  spanClass: "CART_CONTENTS_Q",
  requires: ["CART_CONTENTS","CART_EMPTY"] satisfies readonly RegistryClaimType[],
  markers: [/(?<![a-z])(carrinho|carrinhos|cesta|cestas|sacola|sacolas)/],
} as const;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const CART_CONTENTS_DEFINITION = {
  "type": "CART_CONTENTS",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "cart_contents",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": true,
  "valueBinding": {
    "key": "cart_contents",
    "path": [
      "itemsSummaryText"
    ]
  },
  "valueProjections": [
    {
      "field": "itemsSummaryText",
      "key": "cart_contents",
      "path": [
        "itemsSummaryText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "LITERAL",
        "text": "No seu carrinho: "
      },
      {
        "kind": "PROPOSITION",
        "claimType": "CART_CONTENTS",
        "field": "itemsSummaryText"
      },
      {
        "kind": "LITERAL",
        "text": "."
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "cart_cleared",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const CART_CONTENTS_ID = "CART_CONTENTS@1";

