// @generated by claimdef-compiler from coupon-valid.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): cb1da98d4f0a1e121b41a48763e11efe65d99564b78455fddd80380d34ba31f1
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec, RegistryClaimType } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const COUPON_VALID_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "coupon:valid",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": false,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "coupon:promotions_changed",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "coupon:valid",
    "path": [
      "validityText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const COUPON_VALID_TEMPLATE = {
  "claimType": "COUPON_VALID",
  "posture": "validated",
  "slots": [
    {
      "kind": "PROPOSITION",
      "claimType": "COUPON_VALID",
      "field": "validityText"
    },
    {
      "kind": "LITERAL",
      "text": ". É só informar o código no checkout."
    }
  ]
} satisfies Template;

/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */
export const COUPON_VALID_CLOSURE = {
  spanClass: "COUPON_VALIDITY_Q",
  requires: ["COUPON_VALID","COUPON_INVALID"] satisfies readonly RegistryClaimType[],
  markers: [/(?<![a-z])(?:cupom|cupons|cup[ãa]o|vouchers?|c[óo]digos?\s+(?:de\s+)?(?:desconto|promo[çc][ãa]o|promocional))/],
} as const;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const COUPON_VALID_DEFINITION = {
  "type": "COUPON_VALID",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "coupon:valid",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": false,
  "valueBinding": {
    "key": "coupon:valid",
    "path": [
      "validityText"
    ]
  },
  "valueProjections": [
    {
      "field": "validityText",
      "key": "coupon:valid",
      "path": [
        "validityText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "PROPOSITION",
        "claimType": "COUPON_VALID",
        "field": "validityText"
      },
      {
        "kind": "LITERAL",
        "text": ". É só informar o código no checkout."
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "coupon:promotions_changed",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const COUPON_VALID_ID = "COUPON_VALID@1";

