// @generated by claimdef-compiler from coupon-invalid.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): 55842913db98dc511d072b2d9486946c65f85009d7cfaa8d292b548d4a847e02
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const COUPON_INVALID_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "coupon:invalid",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": false,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "coupon:promotions_changed",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "coupon:invalid",
    "path": [
      "invalidityText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const COUPON_INVALID_TEMPLATE = {
  "claimType": "COUPON_INVALID",
  "posture": "validated",
  "slots": [
    {
      "kind": "PROPOSITION",
      "claimType": "COUPON_INVALID",
      "field": "invalidityText"
    },
    {
      "kind": "LITERAL",
      "text": " — se você tiver outro código, me manda que eu confiro."
    }
  ]
} satisfies Template;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const COUPON_INVALID_DEFINITION = {
  "type": "COUPON_INVALID",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "coupon:invalid",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": false,
  "valueBinding": {
    "key": "coupon:invalid",
    "path": [
      "invalidityText"
    ]
  },
  "valueProjections": [
    {
      "field": "invalidityText",
      "key": "coupon:invalid",
      "path": [
        "invalidityText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "PROPOSITION",
        "claimType": "COUPON_INVALID",
        "field": "invalidityText"
      },
      {
        "kind": "LITERAL",
        "text": " — se você tiver outro código, me manda que eu confiro."
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "coupon:promotions_changed",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const COUPON_INVALID_ID = "COUPON_INVALID@1";

