// @generated by claimdef-compiler from delivery-coverage.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): 4570e4dd701c4c2ca199a3588cdc69b2421365e620d05cf786a6d59fb2489690
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec, RegistryClaimType } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const DELIVERY_COVERAGE_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "delivery:coverage",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": false,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "delivery:zones_changed",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "delivery:coverage",
    "path": [
      "coverageText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const DELIVERY_COVERAGE_TEMPLATE = {
  "claimType": "DELIVERY_COVERAGE",
  "posture": "validated",
  "slots": [
    {
      "kind": "PROPOSITION",
      "claimType": "DELIVERY_COVERAGE",
      "field": "coverageText"
    },
    {
      "kind": "LITERAL",
      "text": ". Confirmo certinho pelo endereço no checkout."
    }
  ]
} satisfies Template;

/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */
export const DELIVERY_COVERAGE_CLOSURE = {
  spanClass: "DELIVERY_COVERAGE_Q",
  requires: ["DELIVERY_COVERAGE","DELIVERY_NO_COVERAGE"] satisfies readonly RegistryClaimType[],
  markers: [/voc[êe]s\s+entregam/, /(?:faz|fazem)\s+entrega/, /entregam?\s+(?:em|no|na|nos|nas|pra|para|at[ée])(?![a-z])/, /(?:onde|at[ée]\s+onde)\s+(?:voc[êe]s\s+)?entregam/, /(?:[áa]rea|regi[õo]es?|regi[ãa]o|zona)\s+de\s+entrega/, /atende[m]?\s+(?:em|no|na|nos|nas)(?![a-z])/, /taxa\s+de\s+(?:entrega|frete)/, /(?:valor|pre[çc]o)\s+d[oa]\s+(?:entrega|frete)/, /quanto\s+(?:custa|fica|sai|[ée])\s+(?:a\s+entrega|o\s+frete)/, /quanto\s+tempo\s+(?:demora|leva)\s+(?:a\s+)?(?:entrega|pra\s+entregar)/],
} as const;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const DELIVERY_COVERAGE_DEFINITION = {
  "type": "DELIVERY_COVERAGE",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "delivery:coverage",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": false,
  "valueBinding": {
    "key": "delivery:coverage",
    "path": [
      "coverageText"
    ]
  },
  "valueProjections": [
    {
      "field": "coverageText",
      "key": "delivery:coverage",
      "path": [
        "coverageText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "PROPOSITION",
        "claimType": "DELIVERY_COVERAGE",
        "field": "coverageText"
      },
      {
        "kind": "LITERAL",
        "text": ". Confirmo certinho pelo endereço no checkout."
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "delivery:zones_changed",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const DELIVERY_COVERAGE_ID = "DELIVERY_COVERAGE@1";

