// @generated by claimdef-compiler from delivery-no-coverage.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): 2dff9ee44207a319cff59870f32a13d742647419267b2b6de448b8a6d5801689
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const DELIVERY_NO_COVERAGE_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "delivery:no_coverage",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": false,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "delivery:zones_changed",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "delivery:no_coverage",
    "path": [
      "noCoverageText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const DELIVERY_NO_COVERAGE_TEMPLATE = {
  "claimType": "DELIVERY_NO_COVERAGE",
  "posture": "validated",
  "slots": [
    {
      "kind": "PROPOSITION",
      "claimType": "DELIVERY_NO_COVERAGE",
      "field": "noCoverageText"
    },
    {
      "kind": "LITERAL",
      "text": " — mas você pode retirar aqui no restaurante, se preferir."
    }
  ]
} satisfies Template;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const DELIVERY_NO_COVERAGE_DEFINITION = {
  "type": "DELIVERY_NO_COVERAGE",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "delivery:no_coverage",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": false,
  "valueBinding": {
    "key": "delivery:no_coverage",
    "path": [
      "noCoverageText"
    ]
  },
  "valueProjections": [
    {
      "field": "noCoverageText",
      "key": "delivery:no_coverage",
      "path": [
        "noCoverageText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "PROPOSITION",
        "claimType": "DELIVERY_NO_COVERAGE",
        "field": "noCoverageText"
      },
      {
        "kind": "LITERAL",
        "text": " — mas você pode retirar aqui no restaurante, se preferir."
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "delivery:zones_changed",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const DELIVERY_NO_COVERAGE_ID = "DELIVERY_NO_COVERAGE@1";

