/**
 * claimdef-compiler GENERATOR (inv.18 v2). Emits the GENERATED runtime artifacts for
 * a claim type FROM its ClaimDefinition source, using the @adjudicate/core
 * `compileClaimDefinition` (the small declarative interpreter). This is the
 * "GENERATE, don't handwrite" half (constraint 5): the def source is the ONLY
 * editable artifact; the registry spec, render template, decomposition closure,
 * validator-wiring definition, and the doc card are all MACHINE-EMITTED with a
 * `@generated` header + a source checksum, and a CI/boot drift guard
 * (`./store-open-now.drift.ts`) re-runs this and fail-closes on any divergence.
 *
 * Run it with:  pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
 *
 * PURE codegen (no clock/RNG/network); the only IO is reading the source file (for
 * its checksum) and writing the generated outputs. Deterministic: same source ⟹
 * byte-identical outputs.
 */

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  type CompiledArtifacts,
  compileClaimDefinition,
} from "@adjudicate/core";
import { STORE_OPEN_NOW_SOURCE } from "./store-open-now.claim.js";

const HERE = dirname(fileURLToPath(import.meta.url));

/** A single claim type's codegen unit: its source file + compiled artifacts. */
interface GenUnit {
  /** The slug used for the generated file names (kebab-case). */
  readonly slug: string;
  /** The source `.claim.ts` file name (for the checksum + the header). */
  readonly sourceFile: string;
  readonly artifacts: CompiledArtifacts;
}

const UNITS: readonly GenUnit[] = [
  {
    slug: "store-open-now",
    sourceFile: "store-open-now.claim.ts",
    artifacts: compileClaimDefinition(STORE_OPEN_NOW_SOURCE),
  },
];

/** sha256 of a generated file's source-of-record (the `.claim.ts`). */
function sourceChecksum(sourceFile: string): string {
  const text = readFileSync(join(HERE, sourceFile), "utf8");
  return createHash("sha256").update(text).digest("hex");
}

/** Serialize a JSON-safe value to a TS object/array literal (stable 2-space indent). */
function tsLiteral(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

/** Serialize an array of RegExp as a TS array of regex LITERALS (JSON can't). */
function regexArrayLiteral(markers: readonly RegExp[]): string {
  return `[${markers.map((m) => m.toString()).join(", ")}]`;
}

const HEADER = (sourceFile: string, checksum: string): string =>
  [
    `// @generated by claimdef-compiler from ${sourceFile} — DO NOT EDIT.`,
    `// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts`,
    `// source-checksum (sha256): ${checksum}`,
    "//",
    "// The editable artifact is the .claim.ts SOURCE; every export below is a pure",
    "// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI",
    "// drift guard (./store-open-now.drift.ts) fail-closes if this file diverges.",
  ].join("\n");

/** Build the GENERATED .ts module content for one unit. */
export function emitGeneratedModule(unit: GenUnit): string {
  const { artifacts: a, sourceFile } = unit;
  const checksum = sourceChecksum(sourceFile);

  // (1) registry spec — assignable to the ibatexas RegistryClaimSpec.
  const registrySpec = tsLiteral(a.registrySpec);

  // (3) render template — wrap the compiled slots in the ibatexas Template shape
  // (claimType keyed + the `validated` posture).
  const template = tsLiteral({
    claimType: a.type,
    posture: "validated",
    slots: a.renderTemplate?.slots ?? [],
  });

  // (7) decomposition closure — spanClass literal + requires + the regex markers.
  const closure = a.closure;

  return [
    HEADER(sourceFile, checksum),
    "",
    `import type { RegistryClaimSpec, RegistryClaimType } from "../claim-registry.js";`,
    `import type { Template } from "../slot-grammar.js";`,
    `import type { ClaimDefinition } from "@adjudicate/core";`,
    "",
    `/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */`,
    `export const STORE_OPEN_NOW_REGISTRY_SPEC = ${registrySpec} satisfies RegistryClaimSpec;`,
    "",
    `/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */`,
    `export const STORE_OPEN_NOW_TEMPLATE = ${template} satisfies Template;`,
    "",
    `/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */`,
    `export const STORE_OPEN_NOW_CLOSURE = {`,
    `  spanClass: ${JSON.stringify(closure?.spanClass ?? "")},`,
    `  requires: ${JSON.stringify(closure?.requires ?? [])} satisfies readonly RegistryClaimType[],`,
    `  markers: ${regexArrayLiteral(closure?.markers ?? [])},`,
    `} as const;`,
    "",
    `/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */`,
    `export const STORE_OPEN_NOW_DEFINITION = ${tsLiteral(a.definition)} satisfies ClaimDefinition;`,
    "",
    `/** The compiled id (type@version) — the designed-in versioning stamp. */`,
    `export const STORE_OPEN_NOW_ID = ${JSON.stringify(a.id)};`,
    "",
  ].join("\n");
}

/** Build the GENERATED .md doc card for one unit. */
export function emitGeneratedDoc(unit: GenUnit): string {
  return unit.artifacts.doc;
}

/** Write all generated outputs to disk. */
export function generateAll(): void {
  for (const unit of UNITS) {
    writeFileSync(join(HERE, `${unit.slug}.generated.ts`), `${emitGeneratedModule(unit)}\n`, "utf8");
    writeFileSync(join(HERE, `${unit.slug}.generated.md`), emitGeneratedDoc(unit), "utf8");
  }
}

export { UNITS };

// Direct-run entrypoint (ESM): regenerate when invoked as a script.
if (process.argv[1] !== undefined && import.meta.url === `file://${process.argv[1]}`) {
  generateAll();
  // eslint-disable-next-line no-console
  console.log(`[claimdef-compiler] generated ${UNITS.length} claim type(s).`);
}
