// @generated by claimdef-compiler from menu-item-allergens.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): 918dab1ac227a9b4a53b54744e16187e6608c468ae9a87cd96039b85dc48c793
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec } from "../claim-registry.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const MENU_ITEM_ALLERGENS_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "allergens",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "static",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": false
} satisfies GeneratedReadClaimSpec;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const MENU_ITEM_ALLERGENS_DEFINITION = {
  "type": "MENU_ITEM_ALLERGENS",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "allergens",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "static",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": false
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const MENU_ITEM_ALLERGENS_ID = "MENU_ITEM_ALLERGENS@1";

