// @generated by claimdef-compiler from menu-pairings.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): d187971141f463346cc5249c07bd6f40d336a548ade71dd63ce56df636f3934b
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec, RegistryClaimType } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const MENU_PAIRINGS_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "menu:pairings",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": false,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "menu:pairings_changed",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "menu:pairings",
    "path": [
      "suggestionsText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const MENU_PAIRINGS_TEMPLATE = {
  "claimType": "MENU_PAIRINGS",
  "posture": "validated",
  "slots": [
    {
      "kind": "PROPOSITION",
      "claimType": "MENU_PAIRINGS",
      "field": "suggestionsText"
    },
    {
      "kind": "LITERAL",
      "text": ". Quer que eu adicione algum ao pedido?"
    }
  ]
} satisfies Template;

/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */
export const MENU_PAIRINGS_CLOSURE = {
  spanClass: "PAIRING_Q",
  requires: ["MENU_PAIRINGS","MENU_SUBSTITUTIONS"] satisfies readonly RegistryClaimType[],
  markers: [/(?<![a-z])(?:no\s+lugar|em\s+vez|ao\s+inv[ée]s|substitui(?:r|ção|cao)?|substitut[oa]s?|troc(?:o|ar|a)\s+por|parecid[oa]\s+com|similar\s+a|acabou|esgotad[oa]|sem\s+estoque|n[ãa]o\s+tem\s+mais)/, /(?<![a-z])(?:combina(?:m|ç[ãa]o|coes|ções)?|vai\s+bem|v[ãa]o\s+bem|acompanha(?:m|mento)?s?|harmoniza(?:m)?|junto\s+com|pedir\s+junto|pra\s+acompanhar|para\s+acompanhar|sugest[ãa]o|sugere|recomenda)/],
} as const;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const MENU_PAIRINGS_DEFINITION = {
  "type": "MENU_PAIRINGS",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "menu:pairings",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": false,
  "valueBinding": {
    "key": "menu:pairings",
    "path": [
      "suggestionsText"
    ]
  },
  "valueProjections": [
    {
      "field": "suggestionsText",
      "key": "menu:pairings",
      "path": [
        "suggestionsText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "PROPOSITION",
        "claimType": "MENU_PAIRINGS",
        "field": "suggestionsText"
      },
      {
        "kind": "LITERAL",
        "text": ". Quer que eu adicione algum ao pedido?"
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "menu:pairings_changed",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const MENU_PAIRINGS_ID = "MENU_PAIRINGS@1";

