// @generated by claimdef-compiler from menu-item-contents.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): b1740ab66d09c795c9f1c6a21b21002d667a478dff0c0158e905b7f26f20f656
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec, RegistryClaimType } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const MENU_ITEM_CONTENTS_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "menu:item_contents",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": {
        "kind": "cacheable",
        "ttl": 300000
      },
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": false,
  "perResourceKey": true,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "menu:item_unpublished",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "menu:item_contents",
    "path": [
      "contentsText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const MENU_ITEM_CONTENTS_TEMPLATE = {
  "claimType": "MENU_ITEM_CONTENTS",
  "posture": "validated",
  "slots": [
    {
      "kind": "PROPOSITION",
      "claimType": "MENU_ITEM_CONTENTS",
      "field": "contentsText"
    },
    {
      "kind": "LITERAL",
      "text": "."
    }
  ]
} satisfies Template;

/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */
export const MENU_ITEM_CONTENTS_CLOSURE = {
  spanClass: "MENU_ITEM_CONTENTS_Q",
  requires: ["MENU_ITEM_CONTENTS"] satisfies readonly RegistryClaimType[],
  markers: [/o que (v[êe]m|t[êe]m|acompanha)/, /do que [ée] (é |)feit/, /que v[êe]m (n|em)/, /composi[çc][ãa]o d/],
} as const;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const MENU_ITEM_CONTENTS_DEFINITION = {
  "type": "MENU_ITEM_CONTENTS",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "menu:item_contents",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": {
        "kind": "cacheable",
        "ttl": 300000
      },
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": false,
  "valueBinding": {
    "key": "menu:item_contents",
    "path": [
      "contentsText"
    ]
  },
  "valueProjections": [
    {
      "field": "contentsText",
      "key": "menu:item_contents",
      "path": [
        "contentsText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "PROPOSITION",
        "claimType": "MENU_ITEM_CONTENTS",
        "field": "contentsText"
      },
      {
        "kind": "LITERAL",
        "text": "."
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "menu:item_unpublished",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const MENU_ITEM_CONTENTS_ID = "MENU_ITEM_CONTENTS@1";

