// @generated by claimdef-compiler from menu-item-price.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): 328ebee3f87f07f1ee8f973b314ed18f543f872ad457021c529dfa05f50d112e
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec, RegistryClaimType } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const MENU_ITEM_PRICE_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "menu:item_price",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": {
        "kind": "cacheable",
        "ttl": 300000
      },
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": false,
  "perResourceKey": true,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "menu:item_unpublished",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "menu:item_price",
    "path": [
      "priceText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const MENU_ITEM_PRICE_TEMPLATE = {
  "claimType": "MENU_ITEM_PRICE",
  "posture": "validated",
  "slots": [
    {
      "kind": "PROPOSITION",
      "claimType": "MENU_ITEM_PRICE",
      "field": "priceText"
    },
    {
      "kind": "LITERAL",
      "text": "."
    }
  ]
} satisfies Template;

/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */
export const MENU_ITEM_PRICE_CLOSURE = {
  spanClass: "MENU_ITEM_PRICE_Q",
  requires: ["MENU_ITEM_PRICE"] satisfies readonly RegistryClaimType[],
  markers: [/quanto custa/, /quanto (custam|é|fica|sai|tá|ta)/, /qual (o |é o )?pre[çc]o/, /pre[çc]o d[aoe]/],
} as const;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const MENU_ITEM_PRICE_DEFINITION = {
  "type": "MENU_ITEM_PRICE",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "menu:item_price",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": {
        "kind": "cacheable",
        "ttl": 300000
      },
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": false,
  "valueBinding": {
    "key": "menu:item_price",
    "path": [
      "priceText"
    ]
  },
  "valueProjections": [
    {
      "field": "priceText",
      "key": "menu:item_price",
      "path": [
        "priceText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "PROPOSITION",
        "claimType": "MENU_ITEM_PRICE",
        "field": "priceText"
      },
      {
        "kind": "LITERAL",
        "text": "."
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "menu:item_unpublished",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const MENU_ITEM_PRICE_ID = "MENU_ITEM_PRICE@1";

