// @generated by claimdef-compiler from menu-overview.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): 7dce3059a0d865361db6c193d7a1ee625b668517c72f19ee61a0bc1036f064bf
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec, RegistryClaimType } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const MENU_OVERVIEW_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "menu:overview",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": {
        "kind": "cacheable",
        "ttl": 300000
      },
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": false,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "menu:item_unpublished",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "menu:overview",
    "path": [
      "overviewText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const MENU_OVERVIEW_TEMPLATE = {
  "claimType": "MENU_OVERVIEW",
  "posture": "validated",
  "slots": [
    {
      "kind": "PROPOSITION",
      "claimType": "MENU_OVERVIEW",
      "field": "overviewText"
    }
  ]
} satisfies Template;

/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */
export const MENU_OVERVIEW_CLOSURE = {
  spanClass: "MENU_OVERVIEW_Q",
  requires: ["MENU_OVERVIEW"] satisfies readonly RegistryClaimType[],
  markers: [/\bcard[áa]pio\b|\bmenu\b/, /o que (voc[êe]s )?(t[êe]m|servem)(?!\s+n[oa]s?\b|\s+em\b)( (pra|para) comer)?/, /quais (os |as )?(pratos|op[çc][õo]es)/],
} as const;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const MENU_OVERVIEW_DEFINITION = {
  "type": "MENU_OVERVIEW",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "menu:overview",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": {
        "kind": "cacheable",
        "ttl": 300000
      },
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": false,
  "valueBinding": {
    "key": "menu:overview",
    "path": [
      "overviewText"
    ]
  },
  "valueProjections": [
    {
      "field": "overviewText",
      "key": "menu:overview",
      "path": [
        "overviewText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "PROPOSITION",
        "claimType": "MENU_OVERVIEW",
        "field": "overviewText"
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "menu:item_unpublished",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const MENU_OVERVIEW_ID = "MENU_OVERVIEW@1";

