// @generated by claimdef-compiler from menu-substitutions.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): 67dafdbca58fd41d4d3e11317c17ad34ada59a9e151a2d1ccafc057664a18ad9
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const MENU_SUBSTITUTIONS_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "menu:substitutions",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": false,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "menu:pairings_changed",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "menu:substitutions",
    "path": [
      "substitutionsText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const MENU_SUBSTITUTIONS_TEMPLATE = {
  "claimType": "MENU_SUBSTITUTIONS",
  "posture": "validated",
  "slots": [
    {
      "kind": "PROPOSITION",
      "claimType": "MENU_SUBSTITUTIONS",
      "field": "substitutionsText"
    },
    {
      "kind": "LITERAL",
      "text": ". Quer que eu troque?"
    }
  ]
} satisfies Template;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const MENU_SUBSTITUTIONS_DEFINITION = {
  "type": "MENU_SUBSTITUTIONS",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "menu:substitutions",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": false,
  "valueBinding": {
    "key": "menu:substitutions",
    "path": [
      "substitutionsText"
    ]
  },
  "valueProjections": [
    {
      "field": "substitutionsText",
      "key": "menu:substitutions",
      "path": [
        "substitutionsText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "PROPOSITION",
        "claimType": "MENU_SUBSTITUTIONS",
        "field": "substitutionsText"
      },
      {
        "kind": "LITERAL",
        "text": ". Quer que eu troque?"
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "menu:pairings_changed",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const MENU_SUBSTITUTIONS_ID = "MENU_SUBSTITUTIONS@1";

