// @generated by claimdef-compiler from order-fulfillment-stage.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): 40e562dad1b5ab4c3a13ade1abf6c2a0f043d8b3b8f9cbbc78662d98cbc5ebdf
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec, RegistryClaimType } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const ORDER_FULFILLMENT_STAGE_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "order_fulfillment_stage",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": true,
  "perResourceKey": true,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "order_cancelled",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "order_fulfillment_stage",
    "path": [
      "fulfillmentStatus"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const ORDER_FULFILLMENT_STAGE_TEMPLATE = {
  "claimType": "ORDER_FULFILLMENT_STAGE",
  "posture": "validated",
  "slots": [
    {
      "kind": "LITERAL",
      "text": "Seu pedido está na etapa: "
    },
    {
      "kind": "PROPOSITION",
      "claimType": "ORDER_FULFILLMENT_STAGE",
      "field": "fulfillmentStatus"
    },
    {
      "kind": "LITERAL",
      "text": "."
    }
  ]
} satisfies Template;

/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */
export const ORDER_FULFILLMENT_STAGE_CLOSURE = {
  spanClass: "ORDER_STATUS_Q",
  requires: ["ORDER_FULFILLMENT_STAGE"] satisfies readonly RegistryClaimType[],
  markers: [/pedido/, /preparo/, /sa[ií]u/, /chegou/, /cad[êe]/, /(?<![a-z])a\s+caminho(?![a-z])/, /(?<![a-z])(?:foi|est[áa]|j[áa])\s+entregue(?![a-z])/, /(?:falta|demora|tempo)[^.!?]{0,20}(?:para|pra)\s+chegar(?!\s+(?:a[íi]|at[ée]|no\s+restaurante|na\s+loja))/],
} as const;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const ORDER_FULFILLMENT_STAGE_DEFINITION = {
  "type": "ORDER_FULFILLMENT_STAGE",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "order_fulfillment_stage",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": true,
  "valueBinding": {
    "key": "order_fulfillment_stage",
    "path": [
      "fulfillmentStatus"
    ]
  },
  "valueProjections": [
    {
      "field": "fulfillmentStatus",
      "key": "order_fulfillment_stage",
      "path": [
        "fulfillmentStatus"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "LITERAL",
        "text": "Seu pedido está na etapa: "
      },
      {
        "kind": "PROPOSITION",
        "claimType": "ORDER_FULFILLMENT_STAGE",
        "field": "fulfillmentStatus"
      },
      {
        "kind": "LITERAL",
        "text": "."
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "order_cancelled",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const ORDER_FULFILLMENT_STAGE_ID = "ORDER_FULFILLMENT_STAGE@1";

