// @generated by claimdef-compiler from payment-status.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): 8737c6ab9b5243ad207d0db4a2f30e6b071fe78b37e688efc063afe933bef35f
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec, RegistryClaimType } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const PAYMENT_STATUS_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "first_party_verified",
  "requiredEvidence": [
    {
      "key": "payment_status",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "first_party_verified",
      "provenancePolicy": "first_party_only"
    }
  ],
  "customerScoped": true,
  "perResourceKey": true,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "payment_refund",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "first_party_verified",
      "provenancePolicy": "first_party_only"
    },
    {
      "key": "payment_chargeback",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "first_party_verified",
      "provenancePolicy": "first_party_only"
    }
  ],
  "valueBinding": {
    "key": "payment_status",
    "path": [
      "status"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const PAYMENT_STATUS_TEMPLATE = {
  "claimType": "PAYMENT_STATUS",
  "posture": "validated",
  "slots": [
    {
      "kind": "LITERAL",
      "text": "O status do seu pagamento é: "
    },
    {
      "kind": "PROPOSITION",
      "claimType": "PAYMENT_STATUS",
      "field": "status"
    },
    {
      "kind": "LITERAL",
      "text": "."
    }
  ]
} satisfies Template;

/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */
export const PAYMENT_STATUS_CLOSURE = {
  spanClass: "PAYMENT_STATUS_Q",
  requires: ["PAYMENT_STATUS"] satisfies readonly RegistryClaimType[],
  markers: [/pago/, /cobran[çc]a/, /pagar/, /paguei/, /aprovad/],
} as const;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const PAYMENT_STATUS_DEFINITION = {
  "type": "PAYMENT_STATUS",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "payment_status",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "first_party_verified",
      "provenancePolicy": "first_party_only"
    }
  ],
  "minSourceIntegrity": "first_party_verified",
  "triadScoped": true,
  "valueBinding": {
    "key": "payment_status",
    "path": [
      "status"
    ]
  },
  "valueProjections": [
    {
      "field": "status",
      "key": "payment_status",
      "path": [
        "status"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "LITERAL",
        "text": "O status do seu pagamento é: "
      },
      {
        "kind": "PROPOSITION",
        "claimType": "PAYMENT_STATUS",
        "field": "status"
      },
      {
        "kind": "LITERAL",
        "text": "."
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "payment_refund",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "first_party_verified",
      "provenancePolicy": "first_party_only"
    },
    {
      "key": "payment_chargeback",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "first_party_verified",
      "provenancePolicy": "first_party_only"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const PAYMENT_STATUS_ID = "PAYMENT_STATUS@1";

