// @generated by claimdef-compiler from payment-history.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): b2f4a066ae29ab3411aa74dfbfb1d73d0aca605e3b8e2a097e93ccc18c1ce832
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec, RegistryClaimType } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const PAYMENT_HISTORY_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "payment_history",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": true,
  "perResourceKey": true,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "payment_history_changed",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "payment_history",
    "path": [
      "historySummaryText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const PAYMENT_HISTORY_TEMPLATE = {
  "claimType": "PAYMENT_HISTORY",
  "posture": "validated",
  "slots": [
    {
      "kind": "LITERAL",
      "text": "Seu histórico de pagamentos: "
    },
    {
      "kind": "PROPOSITION",
      "claimType": "PAYMENT_HISTORY",
      "field": "historySummaryText"
    },
    {
      "kind": "LITERAL",
      "text": "."
    }
  ]
} satisfies Template;

/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */
export const PAYMENT_HISTORY_CLOSURE = {
  spanClass: "PAYMENT_HISTORY_Q",
  requires: ["PAYMENT_HISTORY"] satisfies readonly RegistryClaimType[],
  markers: [/hist[óo]rico[^.!?]{0,25}(pagamento|pagar)/, /(?<![a-z])(meus|todos os meus|[úu]ltimos)\s+pagamentos/],
} as const;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const PAYMENT_HISTORY_DEFINITION = {
  "type": "PAYMENT_HISTORY",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "payment_history",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": true,
  "valueBinding": {
    "key": "payment_history",
    "path": [
      "historySummaryText"
    ]
  },
  "valueProjections": [
    {
      "field": "historySummaryText",
      "key": "payment_history",
      "path": [
        "historySummaryText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "LITERAL",
        "text": "Seu histórico de pagamentos: "
      },
      {
        "kind": "PROPOSITION",
        "claimType": "PAYMENT_HISTORY",
        "field": "historySummaryText"
      },
      {
        "kind": "LITERAL",
        "text": "."
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "payment_history_changed",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const PAYMENT_HISTORY_ID = "PAYMENT_HISTORY@1";

