// @generated by claimdef-compiler from reservation-status.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): 421f638be11fff13c55f8da8a7ab3b3933968bd6a54049227b7d4128b5e0c3aa
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec, RegistryClaimType } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const RESERVATION_STATUS_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "reservation_status",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": true,
  "perResourceKey": true,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "reservation_cancelled",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "reservation_status",
    "path": [
      "statusLine"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const RESERVATION_STATUS_TEMPLATE = {
  "claimType": "RESERVATION_STATUS",
  "posture": "validated",
  "slots": [
    {
      "kind": "LITERAL",
      "text": "O status da sua reserva é: "
    },
    {
      "kind": "PROPOSITION",
      "claimType": "RESERVATION_STATUS",
      "field": "statusLine"
    },
    {
      "kind": "LITERAL",
      "text": "."
    }
  ]
} satisfies Template;

/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */
export const RESERVATION_STATUS_CLOSURE = {
  spanClass: "RESERVATION_STATUS_Q",
  requires: ["RESERVATION_STATUS"] satisfies readonly RegistryClaimType[],
  markers: [/(?<![a-z])reserv(?!at)(a|ar|ad|am|as|ando|ei|ou)/, /(?<![a-z])mesas?(?![a-z])/],
} as const;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const RESERVATION_STATUS_DEFINITION = {
  "type": "RESERVATION_STATUS",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "reservation_status",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": true,
  "valueBinding": {
    "key": "reservation_status",
    "path": [
      "statusLine"
    ]
  },
  "valueProjections": [
    {
      "field": "statusLine",
      "key": "reservation_status",
      "path": [
        "statusLine"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "LITERAL",
        "text": "O status da sua reserva é: "
      },
      {
        "kind": "PROPOSITION",
        "claimType": "RESERVATION_STATUS",
        "field": "statusLine"
      },
      {
        "kind": "LITERAL",
        "text": "."
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "reservation_cancelled",
      "ownershipPolicy": "required",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const RESERVATION_STATUS_ID = "RESERVATION_STATUS@1";

