// @generated by claimdef-compiler from store-open-now.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): 3b6b93c9721afb0edf7086a7ae7077631e58d3aa4a26f99bfb366def81e7d219
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec, RegistryClaimType } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const STORE_OPEN_NOW_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "trusted_service",
  "requiredEvidence": [
    {
      "key": "schedule:store_open_now",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": false,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "schedule:schedule_override",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "schedule:store_open_now",
    "path": [
      "mealPeriod"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const STORE_OPEN_NOW_TEMPLATE = {
  "claimType": "STORE_OPEN_NOW",
  "posture": "validated",
  "slots": [
    {
      "kind": "LITERAL",
      "text": "No momento, o período de funcionamento é: "
    },
    {
      "kind": "PROPOSITION",
      "claimType": "STORE_OPEN_NOW",
      "field": "mealPeriod"
    },
    {
      "kind": "LITERAL",
      "text": "."
    }
  ]
} satisfies Template;

/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */
export const STORE_OPEN_NOW_CLOSURE = {
  spanClass: "STORE_OPEN_NOW_Q",
  requires: ["STORE_OPEN_NOW"] satisfies readonly RegistryClaimType[],
  markers: [/abert/, /fechad/, /que horas/, /funciona/, /hor[áa]rio/],
} as const;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const STORE_OPEN_NOW_DEFINITION = {
  "type": "STORE_OPEN_NOW",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "schedule:store_open_now",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "trusted_service",
  "triadScoped": true,
  "valueBinding": {
    "key": "schedule:store_open_now",
    "path": [
      "mealPeriod"
    ]
  },
  "valueProjections": [
    {
      "field": "mealPeriod",
      "key": "schedule:store_open_now",
      "path": [
        "mealPeriod"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "LITERAL",
        "text": "No momento, o período de funcionamento é: "
      },
      {
        "kind": "PROPOSITION",
        "claimType": "STORE_OPEN_NOW",
        "field": "mealPeriod"
      },
      {
        "kind": "LITERAL",
        "text": "."
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "schedule:schedule_override",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const STORE_OPEN_NOW_ID = "STORE_OPEN_NOW@1";

