// @generated by claimdef-compiler from store-info.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): e3d8713df592482f11ffae21cf3ed7ba4af12acdf6820e2c274bfb94d2c7bb37
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec, RegistryClaimType } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const STORE_INFO_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "structured",
  "requiredEvidence": [
    {
      "key": "store:info",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": {
        "kind": "cacheable",
        "ttl": 300000
      },
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": false,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "store:info_changed",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "store:info",
    "path": [
      "infoText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const STORE_INFO_TEMPLATE = {
  "claimType": "STORE_INFO",
  "posture": "validated",
  "slots": [
    {
      "kind": "PROPOSITION",
      "claimType": "STORE_INFO",
      "field": "infoText"
    }
  ]
} satisfies Template;

/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */
export const STORE_INFO_CLOSURE = {
  spanClass: "STORE_INFO_Q",
  requires: ["STORE_INFO"] satisfies readonly RegistryClaimType[],
  markers: [/onde (fica|é|estão|est[áa]|se localiza)/, /endere[çc]o/, /localiza[çc][ãa]o/, /localizad/, /estacionamento/, /estacionar/, /como (chego|chegar)/],
} as const;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const STORE_INFO_DEFINITION = {
  "type": "STORE_INFO",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "store:info",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": {
        "kind": "cacheable",
        "ttl": 300000
      },
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "structured",
  "triadScoped": false,
  "valueBinding": {
    "key": "store:info",
    "path": [
      "infoText"
    ]
  },
  "valueProjections": [
    {
      "field": "infoText",
      "key": "store:info",
      "path": [
        "infoText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "PROPOSITION",
        "claimType": "STORE_INFO",
        "field": "infoText"
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "store:info_changed",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "structured",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const STORE_INFO_ID = "STORE_INFO@1";

