// @generated by claimdef-compiler from store-hours-for-date.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): c4fb42ba9fca45405bf44c0e0bab6229abe89653ea2c255ca993638e1e425377
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec, RegistryClaimType } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const STORE_HOURS_FOR_DATE_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "trusted_service",
  "requiredEvidence": [
    {
      "key": "schedule:store_hours",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": {
        "kind": "cacheable",
        "ttl": 3600000
      },
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": false,
  "perResourceKey": true,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "schedule:schedule_override",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    },
    {
      "key": "schedule:holiday",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "schedule:store_hours",
    "path": [
      "hoursText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const STORE_HOURS_FOR_DATE_TEMPLATE = {
  "claimType": "STORE_HOURS_FOR_DATE",
  "posture": "validated",
  "slots": [
    {
      "kind": "LITERAL",
      "text": "Nesse dia, nosso horário de funcionamento é: "
    },
    {
      "kind": "PROPOSITION",
      "claimType": "STORE_HOURS_FOR_DATE",
      "field": "hoursText"
    },
    {
      "kind": "LITERAL",
      "text": "."
    }
  ]
} satisfies Template;

/** (7) GENERATED decomposition closure: span class + required companions + pt-BR markers. */
export const STORE_HOURS_FOR_DATE_CLOSURE = {
  spanClass: "STORE_HOURS_FOR_DATE_Q",
  requires: ["STORE_HOURS_FOR_DATE"] satisfies readonly RegistryClaimType[],
  markers: [/hor[áa]rio/, /que horas/, /abre/, /abrem/, /abert/, /fecha/, /funciona/, /expediente/, /atend/],
} as const;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const STORE_HOURS_FOR_DATE_DEFINITION = {
  "type": "STORE_HOURS_FOR_DATE",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "schedule:store_hours",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": {
        "kind": "cacheable",
        "ttl": 3600000
      },
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "trusted_service",
  "triadScoped": false,
  "valueBinding": {
    "key": "schedule:store_hours",
    "path": [
      "hoursText"
    ]
  },
  "valueProjections": [
    {
      "field": "hoursText",
      "key": "schedule:store_hours",
      "path": [
        "hoursText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "LITERAL",
        "text": "Nesse dia, nosso horário de funcionamento é: "
      },
      {
        "kind": "PROPOSITION",
        "claimType": "STORE_HOURS_FOR_DATE",
        "field": "hoursText"
      },
      {
        "kind": "LITERAL",
        "text": "."
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "schedule:schedule_override",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    },
    {
      "key": "schedule:holiday",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const STORE_HOURS_FOR_DATE_ID = "STORE_HOURS_FOR_DATE@1";

