// @generated by claimdef-compiler from store-hours.claim.ts — DO NOT EDIT.
// Regenerate with: pnpm exec tsx apps/api/src/claustrum/claimdefs/generate.ts
// source-checksum (sha256): f95db10fcf8703af447b15cb0523e54428a7c04da9c401d1815b10eb551f2685
//
// The editable artifact is the .claim.ts SOURCE; every export below is a pure
// projection of it computed by @adjudicate/core compileClaimDefinition. A boot/CI
// drift guard (./__tests__/generated-drift.test.ts) fail-closes if this file diverges.

import type { GeneratedReadClaimSpec } from "../claim-registry.js";
import type { Template } from "../slot-grammar.js";
import type { ClaimDefinition } from "@adjudicate/core";

/** (1) GENERATED registry spec row (evidence / falsifiers / value-binding). */
export const STORE_HOURS_REGISTRY_SPEC = {
  "kind": "read_claim",
  "minSourceIntegrity": "trusted_service",
  "requiredEvidence": [
    {
      "key": "schedule:store_hours",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": {
        "kind": "cacheable",
        "ttl": 3600000
      },
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    }
  ],
  "customerScoped": false,
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "schedule:schedule_override",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    },
    {
      "key": "schedule:holiday",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    }
  ],
  "valueBinding": {
    "key": "schedule:store_hours",
    "path": [
      "hoursText"
    ]
  }
} satisfies GeneratedReadClaimSpec;

/** (3) GENERATED render template (proposition slots bound 1:1 to self + field). */
export const STORE_HOURS_TEMPLATE = {
  "claimType": "STORE_HOURS",
  "posture": "validated",
  "slots": [
    {
      "kind": "LITERAL",
      "text": "Hoje nosso horário de funcionamento é: "
    },
    {
      "kind": "PROPOSITION",
      "claimType": "STORE_HOURS",
      "field": "hoursText"
    },
    {
      "kind": "LITERAL",
      "text": "."
    }
  ]
} satisfies Template;

/** (4) GENERATED validator-wiring definition (defense-in-depth for set-level invariants). */
export const STORE_HOURS_DEFINITION = {
  "type": "STORE_HOURS",
  "kind": "read_claim",
  "requiredEvidence": [
    {
      "key": "schedule:store_hours",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": {
        "kind": "cacheable",
        "ttl": 3600000
      },
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    }
  ],
  "minSourceIntegrity": "trusted_service",
  "triadScoped": false,
  "valueBinding": {
    "key": "schedule:store_hours",
    "path": [
      "hoursText"
    ]
  },
  "valueProjections": [
    {
      "field": "hoursText",
      "key": "schedule:store_hours",
      "path": [
        "hoursText"
      ]
    }
  ],
  "renderTemplate": {
    "slots": [
      {
        "kind": "LITERAL",
        "text": "Hoje nosso horário de funcionamento é: "
      },
      {
        "kind": "PROPOSITION",
        "claimType": "STORE_HOURS",
        "field": "hoursText"
      },
      {
        "kind": "LITERAL",
        "text": "."
      }
    ]
  },
  "falsifierComplete": true,
  "falsifiers": [
    {
      "key": "schedule:schedule_override",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    },
    {
      "key": "schedule:holiday",
      "ownershipPolicy": "not_applicable",
      "freshnessPolicy": "must_read_this_turn",
      "sourceIntegrity": "trusted_service",
      "provenancePolicy": "preserve"
    }
  ]
} satisfies ClaimDefinition;

/** The compiled id (type@version) — the designed-in versioning stamp. */
export const STORE_HOURS_ID = "STORE_HOURS@1";

