# Rendered to /opt/ibatexas/docker-compose.yml by user_data.sh.
# Placeholders: $${REGION}, $${ACCOUNT_ID}, $${DOMAIN} (substituted by envsubst
# at boot time, NOT by Terraform).

name: ibatexas

services:
  caddy:
    image: caddy:2-alpine
    container_name: ibatexas-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/ibatexas/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      DOMAIN: $${DOMAIN}
    depends_on:
      - web
      - api
      - admin
    networks: [ibatexas]

  api:
    image: $${ACCOUNT_ID}.dkr.ecr.$${REGION}.amazonaws.com/ibatexas-api:latest
    container_name: ibatexas-api
    restart: unless-stopped
    env_file: /opt/ibatexas/.env
    environment:
      NODE_ENV: production
      APP_ENV: dev
      PORT: "3001"
      TRUST_PROXY: "true"
      RESTAURANT_TIMEZONE: America/Sao_Paulo
      TYPESENSE_HOST: http://typesense:8108
    depends_on:
      - redis
      - nats
      - typesense
    networks: [ibatexas]
    deploy:
      resources:
        limits:
          memory: 512M

  web:
    image: $${ACCOUNT_ID}.dkr.ecr.$${REGION}.amazonaws.com/ibatexas-web:latest
    container_name: ibatexas-web
    restart: unless-stopped
    env_file: /opt/ibatexas/.env
    environment:
      NODE_ENV: production
      APP_ENV: dev
      PORT: "3000"
    networks: [ibatexas]
    deploy:
      resources:
        limits:
          memory: 384M

  admin:
    image: $${ACCOUNT_ID}.dkr.ecr.$${REGION}.amazonaws.com/ibatexas-admin:latest
    container_name: ibatexas-admin
    restart: unless-stopped
    env_file: /opt/ibatexas/.env
    environment:
      NODE_ENV: production
      APP_ENV: dev
      PORT: "3002"
    networks: [ibatexas]
    deploy:
      resources:
        limits:
          memory: 320M

  redis:
    image: redis:7-alpine
    container_name: ibatexas-redis
    restart: unless-stopped
    # Password comes from .env (REDIS_PASSWORD).
    command: ["sh", "-c", "redis-server --requirepass \"$${REDIS_PASSWORD}\""]
    env_file: /opt/ibatexas/.env
    volumes:
      - redis_data:/data
    networks: [ibatexas]
    deploy:
      resources:
        limits:
          memory: 160M

  nats:
    image: nats:2.11-alpine
    container_name: ibatexas-nats
    restart: unless-stopped
    command: ["-js"]
    volumes:
      - nats_data:/data
    networks: [ibatexas]
    deploy:
      resources:
        limits:
          memory: 96M

  typesense:
    image: typesense/typesense:27.1
    container_name: ibatexas-typesense
    restart: unless-stopped
    # Uses the bootstrap key generated by terraform; .env also has the
    # human-usable TYPESENSE_API_KEY. Typesense itself only reads the
    # bootstrap one (fixed per-volume).
    command: >
      --data-dir /data
      --api-key=$${TYPESENSE_BOOTSTRAP_KEY}
      --enable-cors
    env_file: /opt/ibatexas/.env
    volumes:
      - typesense_data:/data
    networks: [ibatexas]
    deploy:
      resources:
        limits:
          memory: 384M

networks:
  ibatexas:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  redis_data:
  nats_data:
  typesense_data:
