"use strict";
/**
 * Pure seed data — no Medusa imports.
 * Exported separately so tests can import it without requiring the Medusa runtime.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SEED_PRODUCTS = exports.CATEGORIES = void 0;
// ─── Category definitions ─────────────────────────────────────────────────────
exports.CATEGORIES = [
    { name: "Restaurante", handle: "restaurante", parent: null },
    { name: "Carnes Defumadas", handle: "carnes-defumadas", parent: "restaurante" },
    { name: "Acompanhamentos", handle: "acompanhamentos", parent: "restaurante" },
    { name: "Sanduíches & Combos", handle: "sanduiches", parent: "restaurante" },
    { name: "Sobremesas", handle: "sobremesas", parent: "restaurante" },
    { name: "Bebidas", handle: "bebidas", parent: "restaurante" },
    { name: "Congelados", handle: "congelados", parent: "restaurante" },
];
// ─── Product definitions ──────────────────────────────────────────────────────
exports.SEED_PRODUCTS = [
    // ── Carnes Defumadas ───────────────────────────────────────────────────────
    {
        title: "Costela Bovina Defumada",
        handle: "costela-bovina-defumada",
        description: "Costela de janela defumada no slow-smoke por 8 horas. Casca crocante com interior suculento e macio. Servida com farofa da casa.",
        categoryHandle: "carnes-defumadas",
        tags: ["popular", "chef_choice", "sem_gluten", "sem_lactose"],
        variants: [
            { title: "500g", price: 8900 },
            { title: "1kg", price: 16500 },
        ],
        metadata: {
            productType: "food",
            availabilityWindow: "jantar",
            preparationTime: 480,
            nutritionalInfo: { calories: 310, protein: 30, fat: 20, carbs: 2, sodium: 520 },
            allergens: [],
        },
    },
    {
        title: "Brisket Americano",
        handle: "brisket-americano",
        description: "Peito bovino defumado lentamente por 10 horas, fatiado na hora. Servido com molho barbecue artesanal da casa.",
        categoryHandle: "carnes-defumadas",
        tags: ["popular", "chef_choice", "sem_gluten", "sem_lactose"],
        variants: [{ title: "400g", price: 7800 }],
        metadata: {
            productType: "food",
            availabilityWindow: "jantar",
            preparationTime: 600,
            nutritionalInfo: { calories: 290, protein: 28, fat: 18, carbs: 3, sodium: 490 },
            allergens: [],
        },
    },
    {
        title: "Frango Defumado Inteiro",
        handle: "frango-defumado-inteiro",
        description: "Frango caipira defumado com ervas aromáticas por 4 horas. Pele dourada e crocante, carne macia e perfumada.",
        categoryHandle: "carnes-defumadas",
        tags: ["popular", "sem_gluten", "sem_lactose"],
        variants: [{ title: "Inteiro (~1,2kg)", price: 5200 }],
        metadata: {
            productType: "food",
            availabilityWindow: "almoco",
            preparationTime: 240,
            nutritionalInfo: { calories: 215, protein: 26, fat: 12, carbs: 0, sodium: 380 },
            allergens: [],
        },
    },
    {
        title: "Barriga de Porco Defumada",
        handle: "barriga-de-porco-defumada",
        description: "Barriga suína defumada com mel e especiarias, finalizada na brasa para casca crocante. Porção generosa.",
        categoryHandle: "carnes-defumadas",
        tags: ["sem_gluten"],
        variants: [{ title: "300g", price: 6200 }],
        metadata: {
            productType: "food",
            availabilityWindow: "jantar",
            preparationTime: 300,
            nutritionalInfo: { calories: 420, protein: 18, fat: 38, carbs: 4, sodium: 610 },
            allergens: [],
        },
    },
    {
        title: "Linguiça Artesanal Defumada",
        handle: "linguica-artesanal-defumada",
        description: "Linguiça suína artesanal defumada com páprica defumada e alho. 4 unidades grelhadas na hora.",
        categoryHandle: "carnes-defumadas",
        tags: ["popular"],
        variants: [{ title: "4 unidades", price: 3800 }],
        metadata: {
            productType: "food",
            availabilityWindow: "almoco",
            preparationTime: 30,
            nutritionalInfo: { calories: 340, protein: 16, fat: 28, carbs: 6, sodium: 780 },
            allergens: ["gluten"],
        },
    },
    {
        title: "Pulled Pork",
        handle: "pulled-pork",
        description: "Paleta suína desfiada defumada por 10 horas. Servida com coleslaw da casa em cima para um contraste perfeito.",
        categoryHandle: "carnes-defumadas",
        tags: ["popular", "sem_gluten", "sem_lactose"],
        variants: [{ title: "300g", price: 4800 }],
        metadata: {
            productType: "food",
            availabilityWindow: "almoco",
            preparationTime: 600,
            nutritionalInfo: { calories: 260, protein: 24, fat: 16, carbs: 5, sodium: 440 },
            allergens: [],
        },
    },
    // ── Acompanhamentos ────────────────────────────────────────────────────────
    {
        title: "Farofa de Bacon Defumado",
        handle: "farofa-de-bacon-defumado",
        description: "Farofa de mandioca tostada com pedaços generosos de bacon defumado, cebola caramelizada e ervas.",
        categoryHandle: "acompanhamentos",
        tags: ["popular"],
        variants: [{ title: "Porção", price: 1600 }],
        metadata: {
            productType: "food",
            availabilityWindow: "almoco",
            preparationTime: 10,
            nutritionalInfo: { calories: 280, protein: 8, fat: 14, carbs: 32, sodium: 520 },
            allergens: [],
        },
    },
    {
        title: "Mandioca Frita",
        handle: "mandioca-frita",
        description: "Mandioca palha cozida e depois frita até dourar. Crocante por fora, macia por dentro. Pura e simples.",
        categoryHandle: "acompanhamentos",
        tags: ["sem_gluten", "sem_lactose", "vegano"],
        variants: [{ title: "Porção", price: 1800 }],
        metadata: {
            productType: "food",
            availabilityWindow: "almoco",
            preparationTime: 15,
            nutritionalInfo: { calories: 210, protein: 2, fat: 8, carbs: 34, sodium: 120 },
            allergens: [],
        },
    },
    {
        title: "Feijão Tropeiro",
        handle: "feijao-tropeiro",
        description: "Feijão carioca refogado com bacon, linguiça, ovos, couve e farinha de mandioca. Clássico mineiro.",
        categoryHandle: "acompanhamentos",
        tags: ["popular"],
        variants: [{ title: "Porção", price: 1800 }],
        metadata: {
            productType: "food",
            availabilityWindow: "almoco",
            preparationTime: 10,
            nutritionalInfo: { calories: 290, protein: 14, fat: 12, carbs: 30, sodium: 580 },
            allergens: ["eggs"],
        },
    },
    {
        title: "Coleslaw da Casa",
        handle: "coleslaw-da-casa",
        description: "Salada de repolho, cenoura e maionese temperada. Refrescante para equilibrar as carnes defumadas.",
        categoryHandle: "acompanhamentos",
        tags: ["sem_gluten", "vegetariano"],
        variants: [{ title: "Porção", price: 1400 }],
        metadata: {
            productType: "food",
            availabilityWindow: "almoco",
            preparationTime: 5,
            nutritionalInfo: { calories: 140, protein: 2, fat: 10, carbs: 10, sodium: 230 },
            allergens: ["eggs", "lactose"],
        },
    },
    {
        title: "Batata Rústica Assada",
        handle: "batata-rustica-assada",
        description: "Batatas em pedaços assadas com azeite, alecrim e sal grosso. Simples e deliciosas.",
        categoryHandle: "acompanhamentos",
        tags: ["sem_gluten", "vegano"],
        variants: [{ title: "Porção", price: 1600 }],
        metadata: {
            productType: "food",
            availabilityWindow: "almoco",
            preparationTime: 30,
            nutritionalInfo: { calories: 175, protein: 3, fat: 5, carbs: 30, sodium: 200 },
            allergens: [],
        },
    },
    // ── Sanduíches & Combos ────────────────────────────────────────────────────
    {
        title: "Smash Burger Defumado",
        handle: "smash-burger-defumado",
        description: "Dois smash patties com carne defumada moída, queijo cheddar derretido, cebola caramelizada e molho especial. Pão brioche artesanal.",
        categoryHandle: "sanduiches",
        tags: ["popular"],
        variants: [{ title: "Unidade", price: 4200 }],
        metadata: {
            productType: "food",
            availabilityWindow: "almoco",
            preparationTime: 15,
            nutritionalInfo: { calories: 680, protein: 38, fat: 38, carbs: 45, sodium: 980 },
            allergens: ["gluten", "lactose"],
        },
    },
    {
        title: "Combo Brisket",
        handle: "combo-brisket",
        description: "400g de brisket fatiado + mandioca frita + bebida 500ml à escolha. O melhor custo-benefício da casa.",
        categoryHandle: "sanduiches",
        tags: ["popular", "sem_gluten"],
        variants: [{ title: "Combo Completo", price: 6800 }],
        metadata: {
            productType: "food",
            availabilityWindow: "almoco",
            preparationTime: 15,
            nutritionalInfo: { calories: 520, protein: 32, fat: 24, carbs: 36, sodium: 610 },
            allergens: [],
        },
    },
    // ── Sobremesas ─────────────────────────────────────────────────────────────
    {
        title: "Brownie com Sorvete",
        handle: "brownie-com-sorvete",
        description: "Brownie de chocolate meio amargo quentinho com bola de sorvete de creme e calda de chocolate.",
        categoryHandle: "sobremesas",
        tags: ["vegetariano"],
        variants: [{ title: "Porção", price: 2200 }],
        metadata: {
            productType: "food",
            availabilityWindow: "almoco",
            preparationTime: 10,
            nutritionalInfo: { calories: 460, protein: 6, fat: 24, carbs: 58, sodium: 180 },
            allergens: ["gluten", "lactose", "eggs"],
        },
    },
    {
        title: "Pudim de Leite Condensado",
        handle: "pudim-de-leite-condensado",
        description: "Pudim clássico cremoso com calda de caramelo. Receita tradicional da casa, feito diariamente.",
        categoryHandle: "sobremesas",
        tags: ["popular", "vegetariano"],
        variants: [{ title: "Fatia", price: 1800 }],
        metadata: {
            productType: "food",
            availabilityWindow: "almoco",
            preparationTime: 5,
            nutritionalInfo: { calories: 320, protein: 8, fat: 10, carbs: 50, sodium: 140 },
            allergens: ["lactose", "eggs"],
        },
    },
    // ── Bebidas ────────────────────────────────────────────────────────────────
    {
        title: "Limonada Suíça",
        handle: "limonada-suica",
        description: "Limonada cremosa com leite condensado, limão tahiti e raspas. Refrescante e equilibrada.",
        categoryHandle: "bebidas",
        tags: ["sem_gluten", "vegetariano"],
        variants: [
            { title: "300ml", price: 1400 },
            { title: "500ml", price: 1900 },
        ],
        metadata: {
            productType: "food",
            availabilityWindow: "always",
            nutritionalInfo: { calories: 140, protein: 2, fat: 4, carbs: 24, sodium: 40 },
            allergens: ["lactose"],
        },
    },
    {
        title: "Cerveja Artesanal IPA",
        handle: "cerveja-artesanal-ipa",
        description: "IPA artesanal com lúpulos frutados e amargor equilibrado. Parceria com cervejaria local.",
        categoryHandle: "bebidas",
        tags: ["sem_gluten"],
        variants: [{ title: "500ml", price: 1800 }],
        metadata: {
            productType: "food",
            availabilityWindow: "always",
            nutritionalInfo: { calories: 170, protein: 2, fat: 0, carbs: 14, sodium: 15 },
            allergens: [],
        },
    },
    {
        title: "Refrigerante",
        handle: "refrigerante",
        description: "Lata gelada 350ml à escolha.",
        categoryHandle: "bebidas",
        tags: ["sem_gluten", "vegano"],
        variants: [
            { title: "Coca-Cola", price: 800 },
            { title: "Guaraná Antarctica", price: 800 },
        ],
        metadata: {
            productType: "food",
            availabilityWindow: "always",
            nutritionalInfo: { calories: 140, protein: 0, fat: 0, carbs: 36, sodium: 45 },
            allergens: [],
        },
    },
    {
        title: "Suco do Dia",
        handle: "suco-do-dia",
        description: "Suco natural 400ml — consulte o sabor do dia no balcão ou pergunte ao nosso assistente.",
        categoryHandle: "bebidas",
        tags: ["sem_gluten"],
        variants: [{ title: "400ml", price: 1200 }],
        metadata: {
            productType: "food",
            availabilityWindow: "almoco",
            nutritionalInfo: { calories: 100, protein: 1, fat: 0, carbs: 24, sodium: 10 },
            allergens: [],
        },
    },
    // ── Congelados ─────────────────────────────────────────────────────────────
    {
        title: "Costela Defumada Congelada",
        handle: "costela-defumada-congelada",
        description: "Costela bovina defumada pré-pronta para aquecer em casa. Congele por até 3 meses. Instruções de preparo inclusas.",
        categoryHandle: "congelados",
        tags: ["congelado", "sem_gluten", "sem_lactose", "popular"],
        variants: [
            { title: "500g (individual)", price: 7200 },
            { title: "1kg (família)", price: 13500 },
        ],
        metadata: {
            productType: "frozen",
            availabilityWindow: "congelados",
            nutritionalInfo: { calories: 310, protein: 30, fat: 20, carbs: 2, sodium: 520 },
            allergens: [],
        },
    },
    {
        title: "Pulled Pork Congelado",
        handle: "pulled-pork-congelado",
        description: "Paleta suína desfiada pré-pronta. Ideal para sanduíches, tacos ou acompanhamento. Congele por até 3 meses.",
        categoryHandle: "congelados",
        tags: ["congelado", "sem_gluten", "sem_lactose"],
        variants: [{ title: "300g", price: 4200 }],
        metadata: {
            productType: "frozen",
            availabilityWindow: "congelados",
            nutritionalInfo: { calories: 260, protein: 24, fat: 16, carbs: 5, sodium: 440 },
            allergens: [],
        },
    },
    {
        title: "Molho Barbecue Artesanal",
        handle: "molho-barbecue-artesanal",
        description: "Nosso molho barbecue defumado para levar para casa. Base de tomate, melado, páprica defumada e especiarias. Congele por até 6 meses.",
        categoryHandle: "congelados",
        tags: ["congelado", "sem_gluten", "sem_lactose", "popular"],
        variants: [{ title: "300ml", price: 2400 }],
        metadata: {
            productType: "frozen",
            availabilityWindow: "congelados",
            nutritionalInfo: { calories: 120, protein: 1, fat: 2, carbs: 26, sodium: 680 },
            allergens: [],
        },
    },
];
//# sourceMappingURL=seed-data.js.map